<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <AssemblyName>CloudDial.Bridge</AssemblyName>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <Version>1.1.0</Version>
    <Copyright>Copyright (c) 2026 Adamperri</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Update="Microsoft.NETCore.App" RuntimeFrameworkVersion="8.0.31" />
    <PackageReference Include="NAudio.Wasapi" Version="2.2.1" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.31" />
    <PackageReference Include="Interop.UIAutomationClient" Version="10.19041.0" />
  </ItemGroup>
</Project>
